In [1]:
import numpy as np
np.set_printoptions(suppress = True , linewidth= 100, precision = 2)

In [2]:
proj_data = np.genfromtxt("loan-data.csv",
                          delimiter = ';',
                          skip_header = 1,
                          autostrip = True)
proj_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [3]:
np.isnan(proj_data).sum()

88005

In [4]:
temp_fill=np.nanmax(proj_data)+1
temp_mean=np.nanmean(proj_data,axis=0)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_16296\939815673.py:2: RuntimeWarning: Mean of empty slice
  temp_mean=np.nanmean(proj_data,axis=0)


In [5]:
temp_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [6]:
temp_stats= np.array([np.nanmin(proj_data, axis= 0),
                    temp_mean,
                    np.nanmax(proj_data, axis= 0)])

C:\Users\lenovo\AppData\Local\Temp\ipykernel_16296\2152800652.py:1: RuntimeWarning: All-NaN slice encountered
  temp_stats= np.array([np.nanmin(proj_data, axis= 0),
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16296\2152800652.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(proj_data, axis= 0)])


In [7]:
temp_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [8]:
column_str= np.argwhere(np.isnan(temp_mean)).squeeze()
column_str

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [9]:
column_num= np.argwhere(np.isnan(temp_mean)== False).squeeze()
column_num

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [10]:
loan_data_str = np.genfromtxt("loan-data.csv", delimiter = ';', 
                              skip_header = 1, 
                              autostrip = True, 
                              usecols =column_str,
                              dtype = np.str_)
loan_data_str

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [11]:
loan_data_num = np.genfromtxt("loan-data.csv", delimiter = ';', 
                              skip_header = 1, 
                              autostrip = True, 
                              usecols =column_num,
                              filling_values= temp_fill)
loan_data_num                        

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [12]:
header_full = np.genfromtxt("loan-data.csv",
                          delimiter = ';',
                          skip_footer = proj_data.shape[0],
                          autostrip = True,
                           dtype= np.str_)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [13]:
header_str, header_num = header_full[column_str], header_full[column_num]

In [14]:
header_str

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [15]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [16]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header= checkpoint_header, data= checkpoint_data)
    checkpoint_variable= np.load(file_name + ".npz")
    return(checkpoint_variable)

In [17]:
checkpoint_test = checkpoint("checkpoint-test", header_str, loan_data_str)

In [18]:
checkpoint_test["data"]

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [19]:
np.array_equal(checkpoint_test["data"],loan_data_str)

True

In [20]:
header_str

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [21]:
header_str[0]= "issue_id"

In [22]:
loan_data_str

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [23]:
loan_data_str[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [24]:
np.unique(loan_data_str[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [25]:
np.chararray.strip(loan_data_str[:,0], "-15")

chararray(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

In [26]:
np.unique(np.chararray.strip(loan_data_str[:,0], "-15"))

chararray(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
          dtype='<U69')

In [27]:
loan_data_str[:,0]= np.chararray.strip(loan_data_str[:,0], "-15")

In [28]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
months

array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      dtype='<U3')

In [29]:
months.size

13

In [30]:
for i in range(13):
    loan_data_str[:,0]= np.where(loan_data_str[:,0] == months[i],
                                i,
                                loan_data_str[:,0])

In [31]:
np.unique(loan_data_str[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [32]:
header_str

array(['issue_id', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [33]:
np.unique(loan_data_str[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [34]:
np.unique(loan_data_str[:,1]).size

9

In [35]:
bad_status= np.array(['','Charged Off','Default','Late (31-120 days)'])

In [36]:
loan_data_str[:,1] = np.where(np.isin(loan_data_str[:,1],bad_status),0,1)

In [37]:
np.unique(loan_data_str[:,1])

array(['0', '1'], dtype='<U69')

In [38]:
loan_data_str[:,2]

array(['36 months', '36 months', '36 months', ..., '36 months', '36 months', '36 months'],
      dtype='<U69')

In [39]:
np.unique(loan_data_str[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [40]:
loan_data_str[:,2]= np.chararray.strip(loan_data_str[:,2], "months")
loan_data_str[:,2]

array(['36 ', '36 ', '36 ', ..., '36 ', '36 ', '36 '], dtype='<U69')

In [41]:
np.unique(loan_data_str[:,2])

array(['', '36 ', '60 '], dtype='<U69')

In [42]:
header_str[2]= 'term_months'

In [43]:
header_str

array(['issue_id', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [44]:
loan_data_str[:,2] = np.where(loan_data_str[:,2]== '',
                             '60',
                             loan_data_str[:,2])
loan_data_str[:,2]

array(['36 ', '36 ', '36 ', ..., '36 ', '36 ', '36 '], dtype='<U69')

In [45]:
np.unique(loan_data_str[:,2])

array(['36 ', '60', '60 '], dtype='<U69')

In [46]:
np.unique(loan_data_str[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [47]:
np.unique(loan_data_str[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [48]:
for i in np.unique(loan_data_str[:,3])[1:]:
    loan_data_str[:,4] = np.where((loan_data_str[:,4]== '')& (loan_data_str[:,3]== i),
                                 i + '5',
                                 loan_data_str[:,4])

In [49]:
np.unique(loan_data_str[:,4],return_counts = True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [50]:
loan_data_str[:,4] = np.where(loan_data_str[:,4] == '',
                             'H1',
                              loan_data_str[:,4]) 

In [51]:
np.unique(loan_data_str[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [52]:
loan_data_str[:,3]

array(['C', 'A', 'B', ..., 'A', 'D', 'A'], dtype='<U69')

In [53]:
loan_data_str = np.delete(loan_data_str, 3, axis =1 )

In [54]:
header_str

array(['issue_id', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [55]:
header_str = np.delete(header_str, 3)

In [56]:
header_str

array(['issue_id', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [57]:
np.unique(loan_data_str[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [58]:
keys = list(np.unique(loan_data_str[:,3]))
values = list(range(1, np.unique(loan_data_str[:,3]).shape[0] +1))
dict_sub_grade = dict(zip(keys, values))

In [59]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [60]:
for i in np.unique(loan_data_str[:,3]):
    loan_data_str[:,3] = np.where(loan_data_str[:,3] == i,
                                  dict_sub_grade[i],
                                  loan_data_str[:,3])

In [61]:
np.unique(loan_data_str[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [62]:
header_str

array(['issue_id', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [63]:
loan_data_str[:,4]

array(['Verified', 'Source Verified', 'Verified', ..., 'Source Verified', 'Source Verified', ''],
      dtype='<U69')

In [64]:
np.unique(loan_data_str[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [65]:
loan_data_str[:,4] = np.where((loan_data_str[:,4] == '') | (loan_data_str[:,4] == 'Not Verified'),0,1)

In [66]:
np.unique(loan_data_str[:,4])

array(['0', '1'], dtype='<U69')

In [67]:
loan_data_str[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [68]:
np.chararray.strip(loan_data_str[:,5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
          dtype='<U69')

In [69]:
loan_data_str[:,5] = np.chararray.strip(loan_data_str[:,5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [70]:
loan_data_str[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [71]:
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [72]:
loan_data_num[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [73]:
loan_data_str[:,5].astype(dtype= np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [74]:
loan_data_num[:,0].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [75]:
np.array_equal(loan_data_str[:,5].astype(dtype= np.int32), loan_data_num[:,0].astype(dtype = np.int32))

True

In [76]:
loan_data_str = np.delete(loan_data_str, 3, axis= 1 )
header_str = np.delete(header_str, 5)

In [77]:
loan_data_str[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [78]:
header_str

array(['issue_id', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [79]:
loan_data_num[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [80]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [81]:
header_str[5] = "state_address"

In [82]:
header_str

array(['issue_id', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [83]:
loan_data_str[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [84]:
np.unique(loan_data_str[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [85]:
np.unique(loan_data_str[:,5], return_counts = True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27], dtype=int64))

In [86]:
state_names, state_counts = np.unique(loan_data_str[:,5], return_counts = True)
state_sorted_counts = np.argsort(-state_counts)
state_names[state_sorted_counts], state_counts[state_sorted_counts]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [87]:
loan_data_str[:,5] = np.where(loan_data_str[:,5] == '',
                             0,
                            loan_data_str[:,5])

In [88]:
state_west = np.array(['WA', 'OR', 'CA', 'NV', 'ID', 'MT', 'WY', 'UT', 'CO', 'AZ', 'NM', 'HI', 'AK'])
state_south =np.array(['TX', 'OK', 'AR', 'LA', 'MS', 'AL', 'TN', 'KY', 'FL', 'GA', 'SC', 'NC', 'VA', 'WV', 'MD', 'DE', 'DC'])
state_midwest =np.array(['ND', 'SD', 'NE', 'KS', 'MN', 'IA', 'MO', 'WI', 'IL', 'IN', 'MI', 'OH'])
state_east =np.array(['PA', 'NY', 'NJ', 'CT', 'MA', 'VT', 'NH', 'ME', 'RI'])

In [89]:
loan_data_str[:,5] = np.where(np.isin(loan_data_str[:,5], state_west), 1, loan_data_str[:,5])
loan_data_str[:,5] = np.where(np.isin(loan_data_str[:,5], state_south), 2, loan_data_str[:,5])
loan_data_str[:,5] = np.where(np.isin(loan_data_str[:,5], state_midwest), 3, loan_data_str[:,5])
loan_data_str[:,5] = np.where(np.isin(loan_data_str[:,5], state_east), 4, loan_data_str[:,5])

In [90]:
np.unique(loan_data_str[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

In [91]:
loan_data_str

array([['5', '1', '36 ', '1', '48010226', '1'],
       ['0', '1', '36 ', '1', '57693261', '4'],
       ['9', '1', '36 ', '1', '59432726', '4'],
       ...,
       ['6', '1', '36 ', '1', '50415990', '1'],
       ['4', '1', '36 ', '1', '46154151', '3'],
       ['12', '1', '36 ', '0', '66055249', '3']], dtype='<U69')

In [92]:
loan_data_str.astype(np.int32)

array([[       5,        1,       36,        1, 48010226,        1],
       [       0,        1,       36,        1, 57693261,        4],
       [       9,        1,       36,        1, 59432726,        4],
       ...,
       [       6,        1,       36,        1, 50415990,        1],
       [       4,        1,       36,        1, 46154151,        3],
       [      12,        1,       36,        0, 66055249,        3]])

In [93]:
loan_data_str = loan_data_str.astype(np.int32)

In [94]:
loan_data_str

array([[       5,        1,       36,        1, 48010226,        1],
       [       0,        1,       36,        1, 57693261,        4],
       [       9,        1,       36,        1, 59432726,        4],
       ...,
       [       6,        1,       36,        1, 50415990,        1],
       [       4,        1,       36,        1, 46154151,        3],
       [      12,        1,       36,        0, 66055249,        3]])

In [95]:
checkpoint_str =checkpoint("checkpoint-str", header_str, loan_data_str)

In [96]:
checkpoint_str["header"]

array(['issue_id', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [97]:
checkpoint_str["data"]

array([[       5,        1,       36,        1, 48010226,        1],
       [       0,        1,       36,        1, 57693261,        4],
       [       9,        1,       36,        1, 59432726,        4],
       ...,
       [       6,        1,       36,        1, 50415990,        1],
       [       4,        1,       36,        1, 46154151,        3],
       [      12,        1,       36,        0, 66055249,        3]])

In [98]:
loan_data_num

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [99]:
np.isnan(loan_data_num).sum()

0

In [100]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [101]:
temp_fill

68616520.0

In [102]:
np.isin(loan_data_num[:,0],temp_fill)

array([False, False, False, ..., False, False, False])

In [103]:
np.isin(loan_data_num[:,0],temp_fill).sum()

0

In [104]:
temp_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [105]:
temp_stats[:, column_num]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [106]:
column_num

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [107]:
loan_data_num[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [108]:
loan_data_num[:,2] = np.where(loan_data_num[:,2] == temp_fill,
                             temp_stats[0, column_num[2]],
                             loan_data_num[:,2])
loan_data_num[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [109]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [110]:
for i in [1,3,4,5]:
    loan_data_num[:,i] = np.where(loan_data_num[:,i] == temp_fill,
                                  temp_stats[2, column_num[i]],
                                 loan_data_num[:,i]) 

In [111]:
loan_data_num

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

In [112]:
eur_usd = np.genfromtxt("EUR-USD.csv", delimiter =',', autostrip =True,dtype =np.str_ )
eur_usd

array([['Open', 'High', 'Low', 'Close', 'Volume'],
       ['1.2098628282546997', '1.2098628282546997', '1.11055588722229', '1.1287955045700073', '0'],
       ['1.1287955045700073', '1.1484194993972778', '1.117680549621582', '1.1205360889434814',
        '0'],
       ['1.119795799255371', '1.1240400075912476', '1.0460032224655151', '1.0830246210098267',
        '0'],
       ['1.0741022825241089', '1.1247594356536865', '1.0521597862243652', '1.1114321947097778',
        '0'],
       ['1.1215037107467651', '1.145304799079895', '1.0821995735168457', '1.0960345268249512',
        '0'],
       ['1.095902442932129', '1.1428401470184326', '1.0888904333114624', '1.122296690940857', '0'],
       ['1.1134989261627197', '1.1219995021820068', '1.081270456314087', '1.0939244031906128',
        '0'],
       ['1.0969001054763794', '1.1705996990203857', '1.0850305557250977', '1.1340054273605347',
        '0'],
       ['1.1225990056991577', '1.1460003852844238', '1.1089695692062378', '1.1255937814712524

In [113]:
eur_usd = np.genfromtxt("EUR-USD.csv", delimiter =',', autostrip =True, skip_header =1, usecols= 3 )
eur_usd

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [114]:
loan_data_str[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [115]:
exchange_rate = loan_data_str[:,0]

for i in range(1,13):
   exchange_rate = np.where(exchange_rate == i,
                            eur_usd[i-1],
                           exchange_rate)
exchange_rate = np.where(exchange_rate == 0,
                         np.mean(eur_usd),
                        exchange_rate) 

exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [116]:
exchange_rate.shape

(10000,)

In [117]:
loan_data_num.shape

(10000, 6)

In [118]:
exchange_rate = np.reshape(exchange_rate, (10000,1))

In [119]:
np.hstack((loan_data_num, exchange_rate))

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [120]:
loan_data_num = np.hstack((loan_data_num, exchange_rate))

In [121]:
loan_data_num

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [122]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [123]:
header_num = np.concatenate(( header_num, np.array(["exchange_rates"])))
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt',
       'exchange_rates'], dtype='<U19')

In [124]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt',
       'exchange_rates'], dtype='<U19')

In [125]:
column_dollars = np.array([1,2,4,5])

In [126]:
loan_data_num[:,[1,2,4,5]]

array([[35000.  , 35000.  ,  1184.86,  9452.96],
       [30000.  , 30000.  ,   938.57,  4679.7 ],
       [15000.  , 15000.  ,   494.86,  1969.83],
       ...,
       [10000.  , 10000.  ,  1372.97,  2185.64],
       [35000.  , 10000.  ,   354.3 ,  3199.4 ],
       [10000.  , 10000.  ,   309.97,   301.9 ]])

In [127]:
loan_data_num[:,[column_dollars]]

array([[[35000.  , 35000.  ,  1184.86,  9452.96]],

       [[30000.  , 30000.  ,   938.57,  4679.7 ]],

       [[15000.  , 15000.  ,   494.86,  1969.83]],

       ...,

       [[10000.  , 10000.  ,  1372.97,  2185.64]],

       [[35000.  , 10000.  ,   354.3 ,  3199.4 ]],

       [[10000.  , 10000.  ,   309.97,   301.9 ]]])

In [128]:
loan_data_num[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [129]:
for i in column_dollars:
    loan_data_num = np.hstack((loan_data_num, np.reshape(loan_data_num[:,i] / loan_data_num[:,6], (10000,1))))

In [130]:
loan_data_num

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [131]:
loan_data_num.shape

(10000, 11)

In [132]:
header_add= np.array([column_name + '_EUR' for column_name in header_num[column_dollars]])

In [133]:
header_add

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [134]:
header_num = np.concatenate((header_num,header_add))

In [135]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt',
       'exchange_rates', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [136]:
header_num[column_dollars]= np.array([column_name + '_USD' for column_name in header_num[column_dollars]])

In [137]:
header_num

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rates', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [138]:
column_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [139]:
header_num[column_index_order]

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR',
       'exchange_rates'], dtype='<U19')

In [140]:
header_num = header_num[column_index_order]

In [141]:
header_num

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR',
       'exchange_rates'], dtype='<U19')

In [142]:
loan_data_num = loan_data_num[:,column_index_order] 

In [143]:
loan_data_num

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

In [144]:
loan_data_num.shape

(10000, 11)

In [145]:
header_num

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR',
       'exchange_rates'], dtype='<U19')

In [146]:
loan_data_num[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [147]:
loan_data_num[:,5] / 100

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

In [148]:
loan_data_num[:,5] = loan_data_num[:,5] / 100

In [149]:
loan_data_num[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

In [151]:
checkpoint_num = checkpoint('checkpoint-num', header_num, loan_data_num)
checkpoint_num['header'], checkpoint_num['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR',
        'exchange_rates'], dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

In [153]:
checkpoint_str["data"].shape

(10000, 6)

In [155]:
checkpoint_num["data"].shape

(10000, 11)

In [157]:
np.hstack((checkpoint_num["data"], checkpoint_str["data"]))

array([[48010226.  ,    35000.  ,    31933.3 , ...,        1.  , 48010226.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        1.  , 57693261.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,        1.  , 59432726.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        1.  , 50415990.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,        1.  , 46154151.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        0.  , 66055249.  ,        3.  ]])

In [159]:
loan_data = np.hstack((checkpoint_num["data"], checkpoint_str["data"]))

In [161]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,        1.  , 48010226.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        1.  , 57693261.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,        1.  , 59432726.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        1.  , 50415990.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,        1.  , 46154151.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        0.  , 66055249.  ,        3.  ]])

In [163]:
np.isnan(loan_data).sum()

0

In [165]:
np.concatenate((checkpoint_num["header"], checkpoint_str["header"]))

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR',
       'exchange_rates', 'issue_id', 'loan_status', 'term_months', 'sub_grade',
       'verification_status', 'state_address'], dtype='<U19')

In [167]:
header_loan = np.concatenate((checkpoint_num["header"], checkpoint_str["header"]))

In [177]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [179]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,        0.  ,   373332.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,        1.  ,   575239.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,        1.  ,   707689.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        1.  , 68614880.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,        1.  , 68615915.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        0.  , 68616519.  ,        2.  ]])

In [203]:
np.vstack((header_loan, loan_data))

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status',
        'state_address'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '0.0', '373332.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '1.0', '575239.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '1.0', '68614880.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '1.0', '68615915.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '0.0', '68616519.0', '2.0']],
      dtype='<U32')

In [205]:
loan_data = np.vstack((header_loan, loan_data))

In [209]:
np.savetxt("Loan-Data-pre.csv", loan_data,
           fmt = "%s", 
           delimiter = ',')